export const locations = [
  "Toàn Quốc",
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Dương",
  "Bình Định",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Cần Thơ",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lạng Sơn",
  "Lào Cai",
  "Lâm Đồng",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];

export const availableTags = [
  "Kỹ thuật",
  "Frontend",
  "Backend",
  "Fullstack",
  "Mobile",
  "DevOps",
  "AI",
  "Machine Learning",
  "Data Science",
  "Data Engineering",
  "UI/UX Design",
  "Game Development",
  "Embedded Systems",
  "Security",
  "Blockchain",
  "Cloud Computing",
  "Testing",
  "Quản lý dự án",
  "Product Management",
  "Agile",
  "Scrum",
  "Career Development",
  "Freelancing",
  "Remote Work",
  "Startups",
  "Kỹ năng mềm",
  "Tiếng Anh chuyên ngành",
  "Git & Version Control",
  "CI/CD",
  "Automation",
  "System Design",
  "Design Patterns",
  "Database Design",
  "API Design",
  "Performance Optimization",
  "Technical Writing",
  "Clean Code",
  "Code Review",
  "Open Source",
  "Dev Tools",
  "Cloud Services",
  "IoT",
  "AR/VR",
  "Big Data",
  "NoSQL",
  "Serverless",
];