export const availableTags: string[] = [
  "Kỹ thuật",
  "Frontend",
  "Backend",
  "Fullstack",
  "Mobile",
  "DevOps",
  "AI",
  "Machine Learning",
  "Data Science",
  "Data Engineering",
  "UI/UX Design",
  "Game Development",
  "Embedded Systems",
  "Security",
  "Blockchain",
  "Cloud Computing",
  "Testing",
  "Quản lý dự án",
  "Product Management",
  "Agile",
  "Scrum",
  "Career Development",
  "Freelancing",
  "Remote Work",
  "Startups",
  "Kỹ năng mềm",
  "Tiếng Anh chuyên ngành",
  "Git & Version Control",
  "CI/CD",
  "Automation",
  "System Design",
  "Design Patterns",
  "Database Design",
  "API Design",
  "Performance Optimization",
  "Technical Writing",
  "Clean Code",
  "Code Review",
  "Open Source",
  "Dev Tools",
  "Cloud Services",
  "IoT",
  "AR/VR",
  "Big Data",
  "NoSQL",
  "Serverless",
];