/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: http://localhost:3000/swagger/json
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthRegisterRequest
 */
export interface AuthRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    password: string;
    /**
     * 
     * @type {number}
     * @memberof AuthRegisterRequest
     */
    roleId: number;
}
