/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CategoryDto
 */
export interface CategoryDto {
  /**
   *
   * @type {number}
   * @memberof CategoryDto
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof CategoryDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CategoryDto
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof CategoryDto
   */
  icon: string;
}
