/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: http://localhost:3000/swagger/json
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CommentUpdateRequest
 */
export interface CommentUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof CommentUpdateRequest
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentUpdateRequest
     */
    postId?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentUpdateRequest
     */
    comment?: string;
    /**
     * 
     * @type {number}
     * @memberof CommentUpdateRequest
     */
    parentId?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentUpdateRequest
     */
    id: number;
}
