/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateNotificationDto
 */
export interface CreateNotificationDto {
  /**
   *
   * @type {string}
   * @memberof CreateNotificationDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationDto
   */
  avatar: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationDto
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationDto
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof CreateNotificationDto
   */
  target: string;
}
