/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JobPostingResponseDto } from "./job-posting-response-dto";
/**
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
  /**
   *
   * @type {Array<JobPostingResponseDto>}
   * @memberof InlineResponse2001
   */
  data?: Array<JobPostingResponseDto>;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2001
   */
  total?: number;
}
