/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface JobPostingResponseDto
 */
export interface JobPostingResponseDto {
  /**
   *
   * @type {number}
   * @memberof JobPostingResponseDto
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof JobPostingResponseDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof JobPostingResponseDto
   */
  slug: string;
  /**
   *
   * @type {number}
   * @memberof JobPostingResponseDto
   */
  salaryMin: number;
  /**
   *
   * @type {number}
   * @memberof JobPostingResponseDto
   */
  salaryMax: number;
  /**
   *
   * @type {string}
   * @memberof JobPostingResponseDto
   */
  location: string;
  /**
   *
   * @type {Date}
   * @memberof JobPostingResponseDto
   */
  deadline: Date;
  /**
   *
   * @type {string}
   * @memberof JobPostingResponseDto
   */
  jobDescription: string;
  /**
   *
   * @type {string}
   * @memberof JobPostingResponseDto
   */
  image: string;
  /**
   *
   * @type {string}
   * @memberof JobPostingResponseDto
   */
  status: JobPostingResponseDtoStatusEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof JobPostingResponseDto
   */
  tags: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof JobPostingResponseDto
   */
  technologies: Array<string>;
  /**
   *
   * @type {Date}
   * @memberof JobPostingResponseDto
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof JobPostingResponseDto
   */
  updatedAt: Date;
  /**
   *
   * @type {number}
   * @memberof JobPostingResponseDto
   */
  userId: number;
}

/**
 * @export
 * @enum {string}
 */
export enum JobPostingResponseDtoStatusEnum {
  Draft = "draft",
  Published = "published",
}
