/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryDto } from "./category-dto";
import { UserDto } from "./user-dto";
/**
 *
 * @export
 * @interface PostCreateResponseDto
 */
export interface PostCreateResponseDto {
  /**
   *
   * @type {number}
   * @memberof PostCreateResponseDto
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PostCreateResponseDto
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof PostCreateResponseDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PostCreateResponseDto
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof PostCreateResponseDto
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof PostCreateResponseDto
   */
  topic: string;
  /**
   *
   * @type {string}
   * @memberof PostCreateResponseDto
   */
  level: string;
  /**
   *
   * @type {string}
   * @memberof PostCreateResponseDto
   */
  image: string;
  /**
   *
   * @type {number}
   * @memberof PostCreateResponseDto
   */
  categoryId: number;
  /**
   *
   * @type {Date}
   * @memberof PostCreateResponseDto
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof PostCreateResponseDto
   */
  updatedAt: Date;
  /**
   *
   * @type {CategoryDto}
   * @memberof PostCreateResponseDto
   */
  category: CategoryDto;
  /**
   *
   * @type {UserDto}
   * @memberof PostCreateResponseDto
   */
  user: UserDto;
}
