/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostUpdateResponse
 */
export interface PostUpdateResponse {
  /**
   *
   * @type {boolean}
   * @memberof PostUpdateResponse
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof PostUpdateResponse
   */
  message: string;
  /**
   *
   * @type {number}
   * @memberof PostUpdateResponse
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PostUpdateResponse
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof PostUpdateResponse
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PostUpdateResponse
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof PostUpdateResponse
   */
  userId: number;
  /**
   *
   * @type {any}
   * @memberof PostUpdateResponse
   */
  data: any;
}
