/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: http://localhost:3000/swagger/json
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryDto } from './category-dto';
import { UserDto } from './user-dto';
/**
 * 
 * @export
 * @interface PostCreateResponse
 */
export interface PostCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof PostCreateResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PostCreateResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreateResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreateResponse
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof PostCreateResponse
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof PostCreateResponse
     */
    topic: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreateResponse
     */
    level: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreateResponse
     */
    image: string;
    /**
     * 
     * @type {number}
     * @memberof PostCreateResponse
     */
    categoryId: number;
    /**
     * 
     * @type {Date}
     * @memberof PostCreateResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PostCreateResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {CategoryDto}
     * @memberof PostCreateResponse
     */
    category: CategoryDto;
    /**
     * 
     * @type {UserDto}
     * @memberof PostCreateResponse
     */
    user: UserDto;
}
