/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostDeleteResponse
 */
export interface PostDeleteResponse {
  /**
   *
   * @type {boolean}
   * @memberof PostDeleteResponse
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof PostDeleteResponse
   */
  message: string;
}
