/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: http://localhost:3000/swagger/json
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PostDeleteRequest
 */
export interface PostDeleteRequest {
    /**
     * 
     * @type {number}
     * @memberof PostDeleteRequest
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PostDeleteRequest
     */
    userId: number;
}
