/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpdateSalaryRangeDto } from "./update-salary-range-dto";
/**
 *
 * @export
 * @interface UpdateJobPostingDto
 */
export interface UpdateJobPostingDto {
  /**
   * Job title
   * @type {string}
   * @memberof UpdateJobPostingDto
   */
  title?: string;
  /**
   *
   * @type {UpdateSalaryRangeDto}
   * @memberof UpdateJobPostingDto
   */
  salary?: UpdateSalaryRangeDto;
  /**
   * Job location
   * @type {string}
   * @memberof UpdateJobPostingDto
   */
  location?: string;
  /**
   * Application deadline
   * @type {string}
   * @memberof UpdateJobPostingDto
   */
  deadline?: string;
  /**
   * Job description
   * @type {string}
   * @memberof UpdateJobPostingDto
   */
  jobDescription?: string;
  /**
   * Tags/Expertise areas
   * @type {Array<string>}
   * @memberof UpdateJobPostingDto
   */
  tags?: Array<string>;
  /**
   * Required technologies
   * @type {Array<string>}
   * @memberof UpdateJobPostingDto
   */
  technologies?: Array<string>;
  /**
   * Image URL
   * @type {string}
   * @memberof UpdateJobPostingDto
   */
  image?: string;
  /**
   * Job posting status
   * @type {string}
   * @memberof UpdateJobPostingDto
   */
  status?: UpdateJobPostingDtoStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateJobPostingDtoStatusEnum {
  Draft = "draft",
  Published = "published",
}
