/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserDto
 */
export interface UserDto {
  /**
   *
   * @type {number}
   * @memberof UserDto
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  fullName: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  avatar: string;
  /**
   *
   * @type {string}
   * @memberof UserDto
   */
  username: string;
}
