/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: http://localhost:3000/swagger/json
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AllUsersResponse
 */
export interface AllUsersResponse {
    /**
     * 
     * @type {number}
     * @memberof AllUsersResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AllUsersResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AllUsersResponse
     */
    fullName: string;
    /**
     * 
     * @type {boolean}
     * @memberof AllUsersResponse
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof AllUsersResponse
     */
    score: string;
    /**
     * 
     * @type {string}
     * @memberof AllUsersResponse
     */
    level: string;
    /**
     * 
     * @type {string}
     * @memberof AllUsersResponse
     */
    avatar: string;
    /**
     * 
     * @type {string}
     * @memberof AllUsersResponse
     */
    bio: string;
    /**
     * 
     * @type {Date}
     * @memberof AllUsersResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AllUsersResponse
     */
    updatedAt: Date;
}
