/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AuthLoginResponse
 */
export interface AuthLoginResponse {
  /**
   * Unique identifier of the user
   * @type {number}
   * @memberof AuthLoginResponse
   */
  id: number;
  /**
   * Username of the user
   * @type {string}
   * @memberof AuthLoginResponse
   */
  username: string;
  /**
   * Full name of the user
   * @type {string}
   * @memberof AuthLoginResponse
   */
  fullName: string;
  /**
   * User role name
   * @type {string}
   * @memberof AuthLoginResponse
   */
  role: string;
  /**
   * User activation status
   * @type {boolean}
   * @memberof AuthLoginResponse
   */
  active: boolean;
  /**
   * User email address
   * @type {string}
   * @memberof AuthLoginResponse
   */
  email: string;
  /**
   * User avatar URL (optional)
   * @type {string}
   * @memberof AuthLoginResponse
   */
  avatar: string;
  /**
   * User bio (optional)
   * @type {string}
   * @memberof AuthLoginResponse
   */
  bio: string;
  /**
   * Access token for authenticated user
   * @type {string}
   * @memberof AuthLoginResponse
   */
  accessToken: string;
  /**
   * User creation date
   * @type {Date}
   * @memberof AuthLoginResponse
   */
  createdAt: Date;
  /**
   * User update date (optional)
   * @type {Date}
   * @memberof AuthLoginResponse
   */
  updatedAt: Date;
}
