/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: http://localhost:3000/swagger/json
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SalaryRangeDto } from './salary-range-dto';
/**
 * 
 * @export
 * @interface CreateJobPostingDto
 */
export interface CreateJobPostingDto {
    /**
     * Job title
     * @type {string}
     * @memberof CreateJobPostingDto
     */
    title: string;
    /**
     * 
     * @type {SalaryRangeDto}
     * @memberof CreateJobPostingDto
     */
    salary: SalaryRangeDto;
    /**
     * Job location
     * @type {string}
     * @memberof CreateJobPostingDto
     */
    location: string;
    /**
     * Application deadline
     * @type {string}
     * @memberof CreateJobPostingDto
     */
    deadline: string;
    /**
     * Job description
     * @type {string}
     * @memberof CreateJobPostingDto
     */
    jobDescription: string;
    /**
     * Tags/Expertise areas
     * @type {Array<string>}
     * @memberof CreateJobPostingDto
     */
    tags: Array<string>;
    /**
     * Required technologies
     * @type {Array<string>}
     * @memberof CreateJobPostingDto
     */
    technologies: Array<string>;
    /**
     * Image URL
     * @type {string}
     * @memberof CreateJobPostingDto
     */
    image?: string;
    /**
     * Job posting status
     * @type {string}
     * @memberof CreateJobPostingDto
     */
    status?: CreateJobPostingDtoStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateJobPostingDtoStatusEnum {
    Draft = 'draft',
    Published = 'published'
}

