/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateTransactionDto
 */
export interface CreateTransactionDto {
  /**
   * Tên người dùng
   * @type {string}
   * @memberof CreateTransactionDto
   */
  username: string;
  /**
   * Ngày ghi sổ
   * @type {string}
   * @memberof CreateTransactionDto
   */
  postingDate: string;
  /**
   * Ngày giao dịch
   * @type {string}
   * @memberof CreateTransactionDto
   */
  transactionDate: string;
  /**
   * Số tiền vào
   * @type {string}
   * @memberof CreateTransactionDto
   */
  creditAmount: string;
  /**
   * Số tiền ra
   * @type {string}
   * @memberof CreateTransactionDto
   */
  debitAmount: string;
  /**
   * Loại tiền tệ
   * @type {string}
   * @memberof CreateTransactionDto
   */
  currency: string;
  /**
   * Nội dung giao dịch
   * @type {string}
   * @memberof CreateTransactionDto
   */
  description: string;
  /**
   * Mã giao dịch (ref)
   * @type {string}
   * @memberof CreateTransactionDto
   */
  refNo: string;
  /**
   * Ngày tạo bản ghi
   * @type {Date}
   * @memberof CreateTransactionDto
   */
  created: Date;
}
