/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostUpdateRequest
 */
export interface PostUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof PostUpdateRequest
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof PostUpdateRequest
   */
  content?: string;
  /**
   *
   * @type {number}
   * @memberof PostUpdateRequest
   */
  userId?: number;
  /**
   *
   * @type {string}
   * @memberof PostUpdateRequest
   */
  topic?: string;
  /**
   *
   * @type {string}
   * @memberof PostUpdateRequest
   */
  level?: string;
  /**
   *
   * @type {string}
   * @memberof PostUpdateRequest
   */
  image?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PostUpdateRequest
   */
  category?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof PostUpdateRequest
   */
  id: number;
}
