/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: https://chodev.dangquochuy.id.vn/swagger/json
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostCreateRequest
 */
export interface PostCreateRequest {
  /**
   *
   * @type {string}
   * @memberof PostCreateRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PostCreateRequest
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof PostCreateRequest
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof PostCreateRequest
   */
  topic: string;
  /**
   *
   * @type {string}
   * @memberof PostCreateRequest
   */
  level: string;
  /**
   *
   * @type {string}
   * @memberof PostCreateRequest
   */
  image: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PostCreateRequest
   */
  category: Array<string>;
}
