/* tslint:disable */
/* eslint-disable */
/**
 * API For My Production
 * My Production API: http://localhost:3000/swagger/json
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateJobPostingDto } from '../models';
import { IdStatusBody } from '../models';
import { JobPostingResponseDto } from '../models';
import { UpdateJobPostingDto } from '../models';
/**
 * JobPostingApi - axios parameter creator
 * @export
 */
export const JobPostingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new job posting
         * @param {CreateJobPostingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobPostControllerCreate: async (body: CreateJobPostingDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling jobPostControllerCreate.');
            }
            const localVarPath = `/api/job-postings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all job postings
         * @param {number} [page] Page number (zero-based)
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobPostControllerFindAll: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/job-postings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a job posting by Slug
         * @param {string} slug Job posting Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobPostControllerFindOne: async (slug: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            if (slug === null || slug === undefined) {
                throw new RequiredError('slug','Required parameter slug was null or undefined when calling jobPostControllerFindOne.');
            }
            const localVarPath = `/api/job-postings/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a job posting
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobPostControllerRemove: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling jobPostControllerRemove.');
            }
            const localVarPath = `/api/job-postings/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a job posting
         * @param {UpdateJobPostingDto} body 
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobPostControllerUpdate: async (body: UpdateJobPostingDto, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling jobPostControllerUpdate.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling jobPostControllerUpdate.');
            }
            const localVarPath = `/api/job-postings/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update job posting status
         * @param {IdStatusBody} body 
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jobPostControllerUpdateStatus: async (body: IdStatusBody, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling jobPostControllerUpdateStatus.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling jobPostControllerUpdateStatus.');
            }
            const localVarPath = `/api/job-postings/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JobPostingApi - functional programming interface
 * @export
 */
export const JobPostingApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new job posting
         * @param {CreateJobPostingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerCreate(body: CreateJobPostingDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JobPostingResponseDto>>> {
            const localVarAxiosArgs = await JobPostingApiAxiosParamCreator(configuration).jobPostControllerCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get all job postings
         * @param {number} [page] Page number (zero-based)
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerFindAll(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<JobPostingResponseDto>>>> {
            const localVarAxiosArgs = await JobPostingApiAxiosParamCreator(configuration).jobPostControllerFindAll(page, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get a job posting by Slug
         * @param {string} slug Job posting Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerFindOne(slug: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JobPostingResponseDto>>> {
            const localVarAxiosArgs = await JobPostingApiAxiosParamCreator(configuration).jobPostControllerFindOne(slug, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete a job posting
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerRemove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await JobPostingApiAxiosParamCreator(configuration).jobPostControllerRemove(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update a job posting
         * @param {UpdateJobPostingDto} body 
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerUpdate(body: UpdateJobPostingDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JobPostingResponseDto>>> {
            const localVarAxiosArgs = await JobPostingApiAxiosParamCreator(configuration).jobPostControllerUpdate(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update job posting status
         * @param {IdStatusBody} body 
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerUpdateStatus(body: IdStatusBody, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<JobPostingResponseDto>>> {
            const localVarAxiosArgs = await JobPostingApiAxiosParamCreator(configuration).jobPostControllerUpdateStatus(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * JobPostingApi - factory interface
 * @export
 */
export const JobPostingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create a new job posting
         * @param {CreateJobPostingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerCreate(body: CreateJobPostingDto, options?: AxiosRequestConfig): Promise<AxiosResponse<JobPostingResponseDto>> {
            return JobPostingApiFp(configuration).jobPostControllerCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all job postings
         * @param {number} [page] Page number (zero-based)
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerFindAll(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<JobPostingResponseDto>>> {
            return JobPostingApiFp(configuration).jobPostControllerFindAll(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a job posting by Slug
         * @param {string} slug Job posting Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerFindOne(slug: string, options?: AxiosRequestConfig): Promise<AxiosResponse<JobPostingResponseDto>> {
            return JobPostingApiFp(configuration).jobPostControllerFindOne(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a job posting
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerRemove(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return JobPostingApiFp(configuration).jobPostControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a job posting
         * @param {UpdateJobPostingDto} body 
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerUpdate(body: UpdateJobPostingDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<JobPostingResponseDto>> {
            return JobPostingApiFp(configuration).jobPostControllerUpdate(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update job posting status
         * @param {IdStatusBody} body 
         * @param {string} id Job posting ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jobPostControllerUpdateStatus(body: IdStatusBody, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<JobPostingResponseDto>> {
            return JobPostingApiFp(configuration).jobPostControllerUpdateStatus(body, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JobPostingApi - object-oriented interface
 * @export
 * @class JobPostingApi
 * @extends {BaseAPI}
 */
export class JobPostingApi extends BaseAPI {
    /**
     * 
     * @summary Create a new job posting
     * @param {CreateJobPostingDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobPostingApi
     */
    public async jobPostControllerCreate(body: CreateJobPostingDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<JobPostingResponseDto>> {
        return JobPostingApiFp(this.configuration).jobPostControllerCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get all job postings
     * @param {number} [page] Page number (zero-based)
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobPostingApi
     */
    public async jobPostControllerFindAll(page?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<JobPostingResponseDto>>> {
        return JobPostingApiFp(this.configuration).jobPostControllerFindAll(page, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get a job posting by Slug
     * @param {string} slug Job posting Slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobPostingApi
     */
    public async jobPostControllerFindOne(slug: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<JobPostingResponseDto>> {
        return JobPostingApiFp(this.configuration).jobPostControllerFindOne(slug, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete a job posting
     * @param {string} id Job posting ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobPostingApi
     */
    public async jobPostControllerRemove(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return JobPostingApiFp(this.configuration).jobPostControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update a job posting
     * @param {UpdateJobPostingDto} body 
     * @param {string} id Job posting ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobPostingApi
     */
    public async jobPostControllerUpdate(body: UpdateJobPostingDto, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<JobPostingResponseDto>> {
        return JobPostingApiFp(this.configuration).jobPostControllerUpdate(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update job posting status
     * @param {IdStatusBody} body 
     * @param {string} id Job posting ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobPostingApi
     */
    public async jobPostControllerUpdateStatus(body: IdStatusBody, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<JobPostingResponseDto>> {
        return JobPostingApiFp(this.configuration).jobPostControllerUpdateStatus(body, id, options).then((request) => request(this.axios, this.basePath));
    }
}
